version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: "http://localhost:8000"
        VITE_WS_BASE: "ws://localhost:8000"
    depends_on:
      - backend
    ports:
      - "5173:80"

